CREATE TABLE PLAYING (
  ACCOUNT_ID TEXT NOT NULL,
  TRACK_ID TEXT NOT NULL,
  AT_TIME TIMESTAMP NOT NULL,
  PRIMARY KEY(ACCOUNT_ID, TRACK_ID, AT_TIME),
  FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID),
  FOREIGN KEY(TRACK_ID) REFERENCES TRACK(ID)
)
